# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Woof' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Woof
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  # Pods for Facebook
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  # Pods for Google
  pod 'GoogleSignIn'

  # Pods for button animation
  pod 'DOFavoriteButton'

  # Pods for swipetablecell
  pod 'MGSwipeTableCell'

  # Pods for Tab Bar Animation
  pod 'RAMAnimatedTabBarController', "~> 2.0.13"


  target 'WoofTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WoofUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
